DROP TABLE IF EXISTS exceptions;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS merchants;

